# Generated by Django 6.0.6 on 2026-06-21 09:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="名前")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "ハード",
                "verbose_name_plural": "ハード",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Maker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="名前")),
                (
                    "furigana",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="フリガナは全角カタカナ、長音符（ー）、半角数字のみ使用できます。",
                                regex="^[ァ-ヶー0-9]+$",
                            )
                        ],
                        verbose_name="フリガナ",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
            ],
            options={
                "verbose_name": "メーカー",
                "verbose_name_plural": "メーカー",
                "ordering": ["furigana"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="タイトル")),
                (
                    "furigana",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="フリガナは全角カタカナ、長音符（ー）、半角数字のみ使用できます。",
                                regex="^[ァ-ヶー0-9]+$",
                            )
                        ],
                        verbose_name="フリガナ",
                    ),
                ),
                (
                    "clear_status",
                    models.CharField(
                        choices=[("clear", "クリア"), ("tsumi", "積み"), ("-", "-")],
                        default="tsumi",
                        max_length=8,
                        verbose_name="クリア状況",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("S+", "S+"),
                            ("S", "S"),
                            ("A", "A"),
                            ("B", "B"),
                            ("C", "C"),
                            ("-", "-"),
                        ],
                        default="-",
                        max_length=4,
                        verbose_name="評価",
                    ),
                ),
                (
                    "is_package",
                    models.BooleanField(default=False, verbose_name="パッケージ所有"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="登録日時"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新日時"),
                ),
                (
                    "cleared_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="クリア日時"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="備考")),
                (
                    "hard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="original_games",
                        to="tsumigee_database.hard",
                        verbose_name="ハード",
                    ),
                ),
                (
                    "play_hard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="playable_games",
                        to="tsumigee_database.hard",
                        verbose_name="プレイ機種",
                    ),
                ),
                (
                    "maker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="games",
                        to="tsumigee_database.maker",
                        verbose_name="メーカー",
                    ),
                ),
            ],
            options={
                "verbose_name": "ゲーム",
                "verbose_name_plural": "ゲーム",
                "ordering": ["furigana"],
            },
        ),
    ]
