# Generated by Django 6.0.6 on 2026-06-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tsumigee_database", "0002_historicalgame_historicalhard_historicalmaker"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="is_bishoujo",
            field=models.BooleanField(default=False, verbose_name="美少女ゲーム"),
        ),
        migrations.AddField(
            model_name="historicalgame",
            name="is_bishoujo",
            field=models.BooleanField(default=False, verbose_name="美少女ゲーム"),
        ),
        migrations.AddField(
            model_name="historicalmaker",
            name="is_bishoujo_brand",
            field=models.BooleanField(
                default=False, verbose_name="美少女ゲームブランド"
            ),
        ),
        migrations.AddField(
            model_name="maker",
            name="is_bishoujo_brand",
            field=models.BooleanField(
                default=False, verbose_name="美少女ゲームブランド"
            ),
        ),
    ]
