# Generated by Django 6.0.6 on 2026-06-21 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tsumigee_database",
            "0003_game_is_bishoujo_historicalgame_is_bishoujo_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="game",
            old_name="is_bishoujo",
            new_name="is_bishojo",
        ),
        migrations.RenameField(
            model_name="historicalgame",
            old_name="is_bishoujo",
            new_name="is_bishojo",
        ),
        migrations.RenameField(
            model_name="historicalmaker",
            old_name="is_bishoujo_brand",
            new_name="is_bishojo_brand",
        ),
        migrations.RenameField(
            model_name="maker",
            old_name="is_bishoujo_brand",
            new_name="is_bishojo_brand",
        ),
        migrations.AlterField(
            model_name="game",
            name="clear_status",
            field=models.CharField(
                choices=[
                    ("clear", "クリア"),
                    ("tsumi", "積み"),
                    ("collection_only", "コレクションのみ"),
                ],
                default="tsumi",
                max_length=15,
                verbose_name="クリア状況",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="play_hard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playable_games",
                to="tsumigee_database.hard",
                verbose_name="プレイ可能ハード",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgame",
            name="clear_status",
            field=models.CharField(
                choices=[
                    ("clear", "クリア"),
                    ("tsumi", "積み"),
                    ("collection_only", "コレクションのみ"),
                ],
                default="tsumi",
                max_length=15,
                verbose_name="クリア状況",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgame",
            name="play_hard",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tsumigee_database.hard",
                verbose_name="プレイ可能ハード",
            ),
        ),
    ]
