# Generated by Django 6.0.6 on 2026-06-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tsumigee_database", "0004_rename_is_bishoujo_game_is_bishojo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="cleared_at",
            field=models.DateField(blank=True, null=True, verbose_name="クリア日"),
        ),
        migrations.AlterField(
            model_name="historicalgame",
            name="cleared_at",
            field=models.DateField(blank=True, null=True, verbose_name="クリア日"),
        ),
    ]
