# Generated by Django 6.0.6 on 2026-06-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tsumigee_database", "0005_alter_game_cleared_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="clear_status",
            field=models.CharField(
                choices=[
                    ("clear", "クリア"),
                    ("tsumi", "積み"),
                    ("collection_only", "収集のみ"),
                ],
                default="tsumi",
                max_length=15,
                verbose_name="クリア状況",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgame",
            name="clear_status",
            field=models.CharField(
                choices=[
                    ("clear", "クリア"),
                    ("tsumi", "積み"),
                    ("collection_only", "収集のみ"),
                ],
                default="tsumi",
                max_length=15,
                verbose_name="クリア状況",
            ),
        ),
    ]
