# Generated by Django 6.0.6 on 2026-06-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tsumigee_database", "0006_alter_game_clear_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hard",
            name="name",
            field=models.CharField(max_length=32, unique=True, verbose_name="名前"),
        ),
        migrations.AlterField(
            model_name="historicalhard",
            name="name",
            field=models.CharField(db_index=True, max_length=32, verbose_name="名前"),
        ),
        migrations.AlterField(
            model_name="historicalmaker",
            name="name",
            field=models.CharField(db_index=True, max_length=255, verbose_name="名前"),
        ),
        migrations.AlterField(
            model_name="maker",
            name="name",
            field=models.CharField(max_length=255, unique=True, verbose_name="名前"),
        ),
    ]
