# Generated by Django 6.0.6 on 2026-06-27 08:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tsumigee_database", "0007_add_unique_constraints"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="clear_status",
            field=models.CharField(
                choices=[
                    ("clear", "クリア"),
                    ("tsumi", "積み"),
                    ("collection_only", "収集のみ"),
                ],
                db_index=True,
                default="tsumi",
                max_length=15,
                verbose_name="クリア状況",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="furigana",
            field=models.CharField(
                db_index=True,
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="フリガナは全角カタカナ、長音符（ー）、半角数字のみ使用できます。",
                        regex="^[ァ-ヶー0-9]+$",
                    )
                ],
                verbose_name="フリガナ",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="grade",
            field=models.CharField(
                choices=[
                    ("S+", "S+"),
                    ("S", "S"),
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("-", "-"),
                ],
                db_index=True,
                default="-",
                max_length=4,
                verbose_name="評価",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgame",
            name="clear_status",
            field=models.CharField(
                choices=[
                    ("clear", "クリア"),
                    ("tsumi", "積み"),
                    ("collection_only", "収集のみ"),
                ],
                db_index=True,
                default="tsumi",
                max_length=15,
                verbose_name="クリア状況",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgame",
            name="furigana",
            field=models.CharField(
                db_index=True,
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="フリガナは全角カタカナ、長音符（ー）、半角数字のみ使用できます。",
                        regex="^[ァ-ヶー0-9]+$",
                    )
                ],
                verbose_name="フリガナ",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgame",
            name="grade",
            field=models.CharField(
                choices=[
                    ("S+", "S+"),
                    ("S", "S"),
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("-", "-"),
                ],
                db_index=True,
                default="-",
                max_length=4,
                verbose_name="評価",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmaker",
            name="furigana",
            field=models.CharField(
                db_index=True,
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="フリガナは全角カタカナ、長音符（ー）、半角数字のみ使用できます。",
                        regex="^[ァ-ヶー0-9]+$",
                    )
                ],
                verbose_name="フリガナ",
            ),
        ),
        migrations.AlterField(
            model_name="maker",
            name="furigana",
            field=models.CharField(
                db_index=True,
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="フリガナは全角カタカナ、長音符（ー）、半角数字のみ使用できます。",
                        regex="^[ァ-ヶー0-9]+$",
                    )
                ],
                verbose_name="フリガナ",
            ),
        ),
    ]
